// Generated by gencpp from file MAF3_msgs/MAF3_Raw.msg
// DO NOT EDIT!


#ifndef MAF3_MSGS_MESSAGE_MAF3_RAW_H
#define MAF3_MSGS_MESSAGE_MAF3_RAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace MAF3_msgs
{
template <class ContainerAllocator>
struct MAF3_Raw_
{
  typedef MAF3_Raw_<ContainerAllocator> Type;

  MAF3_Raw_()
    : header()
    , Fz(0)
    , Mx(0)
    , My(0)  {
    }
  MAF3_Raw_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Fz(0)
    , Mx(0)
    , My(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _Fz_type;
  _Fz_type Fz;

   typedef uint16_t _Mx_type;
  _Mx_type Mx;

   typedef uint16_t _My_type;
  _My_type My;





  typedef boost::shared_ptr< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> const> ConstPtr;

}; // struct MAF3_Raw_

typedef ::MAF3_msgs::MAF3_Raw_<std::allocator<void> > MAF3_Raw;

typedef boost::shared_ptr< ::MAF3_msgs::MAF3_Raw > MAF3_RawPtr;
typedef boost::shared_ptr< ::MAF3_msgs::MAF3_Raw const> MAF3_RawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator1> & lhs, const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Fz == rhs.Fz &&
    lhs.Mx == rhs.Mx &&
    lhs.My == rhs.My;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator1> & lhs, const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace MAF3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2737879b757edf1b6829d2f9ca33456";
  }

  static const char* value(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2737879b757edf1ULL;
  static const uint64_t static_value2 = 0xb6829d2f9ca33456ULL;
};

template<class ContainerAllocator>
struct DataType< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MAF3_msgs/MAF3_Raw";
  }

  static const char* value(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint16 Fz\n"
"uint16 Mx\n"
"uint16 My\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Fz);
      stream.next(m.Mx);
      stream.next(m.My);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MAF3_Raw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Fz: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Fz);
    s << indent << "Mx: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Mx);
    s << indent << "My: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.My);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAF3_MSGS_MESSAGE_MAF3_RAW_H
