// Generated by gencpp from file MAF3_msgs/MAF3_Raw.msg
// DO NOT EDIT!


#ifndef MAF3_MSGS_MESSAGE_MAF3_RAW_H
#define MAF3_MSGS_MESSAGE_MAF3_RAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace MAF3_msgs
{
template <class ContainerAllocator>
struct MAF3_Raw_
{
  typedef MAF3_Raw_<ContainerAllocator> Type;

  MAF3_Raw_()
    : Fz(0)
    , Mx(0)
    , My(0)  {
    }
  MAF3_Raw_(const ContainerAllocator& _alloc)
    : Fz(0)
    , Mx(0)
    , My(0)  {
  (void)_alloc;
    }



   typedef uint16_t _Fz_type;
  _Fz_type Fz;

   typedef uint16_t _Mx_type;
  _Mx_type Mx;

   typedef uint16_t _My_type;
  _My_type My;





  typedef boost::shared_ptr< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> const> ConstPtr;

}; // struct MAF3_Raw_

typedef ::MAF3_msgs::MAF3_Raw_<std::allocator<void> > MAF3_Raw;

typedef boost::shared_ptr< ::MAF3_msgs::MAF3_Raw > MAF3_RawPtr;
typedef boost::shared_ptr< ::MAF3_msgs::MAF3_Raw const> MAF3_RawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator1> & lhs, const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator2> & rhs)
{
  return lhs.Fz == rhs.Fz &&
    lhs.Mx == rhs.Mx &&
    lhs.My == rhs.My;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator1> & lhs, const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace MAF3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88234e0056df7c10f369a7d34efefabf";
  }

  static const char* value(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88234e0056df7c10ULL;
  static const uint64_t static_value2 = 0xf369a7d34efefabfULL;
};

template<class ContainerAllocator>
struct DataType< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MAF3_msgs/MAF3_Raw";
  }

  static const char* value(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 Fz\n"
"uint16 Mx\n"
"uint16 My\n"
;
  }

  static const char* value(const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Fz);
      stream.next(m.Mx);
      stream.next(m.My);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MAF3_Raw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::MAF3_msgs::MAF3_Raw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::MAF3_msgs::MAF3_Raw_<ContainerAllocator>& v)
  {
    s << indent << "Fz: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Fz);
    s << indent << "Mx: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Mx);
    s << indent << "My: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.My);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAF3_MSGS_MESSAGE_MAF3_RAW_H
